language: node_js
node_js:
  - '8'
  - "10"
  - '12'
sudo: false
cache: 
  yarn: true
before_install:
  - npm install --global yarn
install:
  - yarn
script:
  - yarn test
  - yarn add ava@2.1.0 --dev -W
  - yarn test
